name: Shared Jobs

on:
  workflow_call:

jobs:
  changelog-update-checker:
    name: Check changelog update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify changelog updates
        run: |
          ./.github/scripts/check_changelog_update.sh