{
 "title": "Ragbits example",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Prompt Throughput (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum by(le, model) (\n        rate(ragbits_prompt_throughput_seconds_bucket[$__interval])\n          ) > 0\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token throughput (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum by(le, model) (\n        rate(ragbits_token_throughput_tokens_per_second_bucket[$__interval])\n          ) > 0\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input tokens (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum by(le, model) (\n        rate(ragbits_input_tokens_bucket[$__interval])\n          ) > 0\n          )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}