type: ragbits.core.embeddings.litellm:LiteLLMEmbedder
config:
  optimize: true
  choices:
    - model: "text-embedding-3-small"
      default_options:
        dimensions:
          optimize: true
          range:
            - 32
            - 512
        encoding_format: float
    - model: "text-embedding-3-large"
      default_options:
        dimensions:
          optimize: true
          range:
            - 512
            - 1024
        encoding_format: float