"""Regression tests for :class:`RagbitsChatModelProvider`.

The provider is the single source of truth that drives TypeScript schema
generation. Any Pydantic request/response model that becomes part of the HTTP
surface must be registered here or the autogenerated client will silently drift
from the backend. The guard below enumerates the public models in
``ragbits.chat.interface.types`` and fails when one is missing, so adding a new
API model forces an explicit decision to expose or exclude it.
"""

from __future__ import annotations

import inspect

from pydantic import BaseModel

from ragbits.chat.interface import types as chat_types
from ragbits.chat.providers import RagbitsChatModelProvider

# Models that intentionally live outside the autogen surface. They are either
# abstract bases or streaming wrappers that the generator expands into a
# hand-written union type (see ``_generate_chat_response_union_type`` in
# ``scripts/generate_typescript_from_json_schema.py``).
_EXCLUDED_MODELS: frozenset[str] = frozenset(
    {
        "ResponseContent",
        "ChatResponse",
        "TextResponse",
        "ReferenceResponse",
        "StateUpdateResponse",
        "MessageIdResponse",
        "ConversationIdResponse",
        "ConversationSummaryResponse",
        "LiveUpdateResponse",
        "FollowupMessagesResponse",
        "ImageResponse",
        "ChunkedContentResponse",
        "ClearMessageResponse",
        "UsageResponse",
        "PlanItemResponse",
        "ConfirmationRequestResponse",
        "ErrorResponse",
        "ClearMessageContent",
    }
)


def _public_api_models() -> dict[str, type[BaseModel]]:
    """Collect the public Pydantic models declared in ``interface.types``.

    We look up models by *class identity* rather than by name so a model can be
    registered in the provider under an alias (e.g. ``ChatMessageRequest`` is
    registered as ``ChatRequest``).
    """
    models: dict[str, type[BaseModel]] = {}
    for name, obj in inspect.getmembers(chat_types, inspect.isclass):
        if not issubclass(obj, BaseModel) or obj is BaseModel:
            continue
        if obj.__module__ != chat_types.__name__:
            continue
        if inspect.isabstract(obj):
            continue
        if "[" in obj.__name__ or name in _EXCLUDED_MODELS:
            continue
        models[name] = obj
    return models


def test_all_public_models_are_registered_in_provider() -> None:
    registered_classes = set(RagbitsChatModelProvider().get_models().values())
    missing = [name for name, cls in _public_api_models().items() if cls not in registered_classes]
    assert not missing, (
        "The following models are declared in ragbits.chat.interface.types but "
        "are not registered in RagbitsChatModelProvider. They will not be "
        "emitted to autogen.types.ts. Either register them or add them to "
        f"_EXCLUDED_MODELS with an explicit comment: {sorted(missing)}"
    )


def test_share_models_are_registered() -> None:
    """Explicit guard for the conversation-sharing models.

    Sharing went through the autogen pipeline late, so this test protects the
    concrete names from being removed by accident.
    """
    registered = RagbitsChatModelProvider().get_models()
    for name in (
        "ShareConversationRequest",
        "ConversationShareResponse",
        "ConversationMeta",
        "ConversationDetail",
    ):
        assert name in registered, f"{name} must be registered in RagbitsChatModelProvider"
