defaults:
  - dataloader@evaluation.dataloader: hf
  - pipeline@evaluation.pipeline: document_search
  - metrics@evaluation.metrics:
    - precision_recall_f1
    - ranked_retrieval
  - _self_

logger:
  local: True
  neptune: False
