"""Integration test ensuring summaries generated by the metadata decorator
are persisted and surfaced through ``SQLHistoryPersistence``.

Regression coverage for a bug where the conversation owner saw a stale title
(e.g. the heuristic ``"New chat"`` value cached in the in-memory store) while
recipients of a shared conversation saw a different summary because the
``ConversationSummaryResponse`` was streamed to the client but never recorded
into the persistence layer.
"""

from collections.abc import AsyncGenerator

import pytest
from sqlalchemy.ext.asyncio import create_async_engine

from ragbits.chat.auth.types import User
from ragbits.chat.interface import ChatInterface
from ragbits.chat.interface.summary import HeuristicSummaryGenerator
from ragbits.chat.interface.types import ChatContext, ChatResponse, ChatResponseUnion
from ragbits.chat.persistence.sql import SQLHistoryPersistence
from ragbits.core.prompt.base import ChatFormat


class _TextOnlyChat(ChatInterface):
    """Minimal chat that only streams text — relies on the decorator to emit summary."""

    summary_generator = HeuristicSummaryGenerator()

    def __init__(self, persistence: SQLHistoryPersistence) -> None:
        self.history_persistence = persistence

    async def chat(
        self,
        message: str,
        history: ChatFormat,
        context: ChatContext,
    ) -> AsyncGenerator[ChatResponseUnion, None]:
        yield self.create_text_response(f"echo: {message}")


@pytest.fixture
async def persistence() -> SQLHistoryPersistence:
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    return SQLHistoryPersistence(engine)


async def _drive(chat: _TextOnlyChat, context: ChatContext, message: str) -> list[ChatResponse]:
    """Iterate the wrapped ``chat`` generator and collect the streamed responses."""
    collected: list[ChatResponse] = []
    async for response in chat.chat(message, [], context):
        collected.append(response)
    return collected


@pytest.mark.asyncio
async def test_heuristic_summary_is_persisted_for_new_conversation(persistence: SQLHistoryPersistence) -> None:
    chat = _TextOnlyChat(persistence)
    user = User(user_id="alice", username="alice")
    context = ChatContext(user=user)

    await _drive(chat, context, "what is python and why is it popular")

    assert context.conversation_id is not None
    summaries = await persistence.get_conversation_summaries([context.conversation_id])
    assert summaries[context.conversation_id] == "what is python and why is"


@pytest.mark.asyncio
async def test_heuristic_summary_matches_streamed_summary(persistence: SQLHistoryPersistence) -> None:
    """The persisted summary must equal the one the client receives in the stream."""
    chat = _TextOnlyChat(persistence)
    user = User(user_id="alice", username="alice")
    context = ChatContext(user=user)

    streamed = await _drive(chat, context, "what is python and why is it popular")

    streamed_summary = next(
        (r.content.summary for r in streamed if r.get_type() == "conversation_summary"),
        None,
    )
    assert streamed_summary is not None

    assert context.conversation_id is not None
    summaries = await persistence.get_conversation_summaries([context.conversation_id])
    assert summaries[context.conversation_id] == streamed_summary


@pytest.mark.asyncio
async def test_short_message_persists_fallback_title(persistence: SQLHistoryPersistence) -> None:
    """Heuristic returns the configured fallback for trivially short messages."""
    chat = _TextOnlyChat(persistence)
    user = User(user_id="alice", username="alice")
    context = ChatContext(user=user)

    await _drive(chat, context, "hi")

    assert context.conversation_id is not None
    summaries = await persistence.get_conversation_summaries([context.conversation_id])
    assert summaries[context.conversation_id] == "New chat"
