type: ragbits.evaluate.dataloaders.document_search:DocumentSearchDataLoader
config:
  source:
    type: ragbits.core.sources:HuggingFaceSource
    config:
      path: "deepsense-ai/synthetic-rag-dataset_v1.0"
      split: "train"
