name: 'Test Built Packages'
description: 'Sets up environment from built packages and runs tests'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  google-drive-clientid-json:
    description: 'Google Drive client ID JSON'
    required: false
  google-source-unit-test-folder:
    description: 'Google source unit test folder'
    required: false
  google-drive-target-email:
    description: 'Google Drive target email'
    required: false

runs:
  using: "composite"
  steps:
    - name: Test Each Package Separately
      shell: bash
      run: |
        # Define packages and their extras
        declare -A PACKAGE_EXTRAS=(
          ["ragbits-core"]="chroma,hf,s3,gcs,azure,local,openai,otel,logfire,promptfoo,qdrant,fastembed,fastembed-gpu,pgvector,weaviate,google-drive"
          ["ragbits-agents"]="a2a,mcp,cli"
          ["ragbits-chat"]="sql"
          ["ragbits-cli"]=""
          ["ragbits-evaluate"]="relari"
          ["ragbits-guardrails"]="openai"
          ["ragbits-document-search"]="ray,unstructured"
        )

        # Track overall success
        FAILED_PACKAGES=()

        echo "Testing packages with Python ${{ inputs.python-version }}"

        # Test each package
        for package in "${!PACKAGE_EXTRAS[@]}"; do
          echo "========================================="
          echo "Testing $package"
          echo "========================================="

          # Remove existing venv if present
          rm -rf .venv

          # Create a fresh virtual environment
          uv venv --python ${{ inputs.python-version }}

          # Convert package name to wheel format (hyphens to underscores)
          wheel_package_name="${package//-/_}"

          # Find the wheel file for this package
          wheel_file=$(ls dist/${wheel_package_name}-*.whl 2>/dev/null || echo "")

          if [ -z "$wheel_file" ]; then
            echo "Warning: No wheel found for $package (searched for ${wheel_package_name}-*.whl), skipping..."
            continue
          fi

          # Install the package with all its extras
          extras="${PACKAGE_EXTRAS[$package]}"
          if [ -n "$extras" ]; then
            echo "Installing $wheel_file with extras: $extras"
            uv pip install --find-links dist "${wheel_file}[$extras]"
          else
            echo "Installing $wheel_file without extras"
            uv pip install --find-links dist "$wheel_file"
          fi

          # Install additional dependencies for specific packages
          if [ "$package" == "ragbits-document-search" ]; then
            uv pip install pyarrow==17.0.0 ray==2.43.0
          fi

          # Install test dependencies
          uv pip install pytest~=8.3.3 pytest-cov~=5.0.0 pytest-asyncio~=0.24.0 pytest-postgresql~=7.0.1 moto~=4.2.7 aiosqlite~=0.21.0

          # Determine test directory
          test_dir="packages/${package}/tests"

          if [ ! -d "$test_dir" ]; then
            echo "Warning: Test directory $test_dir not found, skipping tests for $package"
            continue
          fi

          # Run tests for this package only
          echo "Running tests from $test_dir"
          if uv run --no-sync pytest "$test_dir" --postgresql-password postgres -v -p no:warnings; then
            echo "✓ Tests passed for $package"
          else
            echo "✗ Tests failed for $package"
            FAILED_PACKAGES+=("$package")
          fi

          echo ""
        done

        # Report results
        echo "========================================="
        echo "Test Summary"
        echo "========================================="

        if [ ${#FAILED_PACKAGES[@]} -eq 0 ]; then
          echo "✓ All packages tested successfully!"
        else
          echo "✗ Failed packages: ${FAILED_PACKAGES[*]}"
          exit 1
        fi
      env:
        GOOGLE_DRIVE_CLIENTID_JSON: ${{ inputs.google-drive-clientid-json }}
        GOOGLE_SOURCE_UNIT_TEST_FOLDER: ${{ inputs.google-source-unit-test-folder }}
        GOOGLE_DRIVE_TARGET_EMAIL: ${{ inputs.google-drive-target-email }}
