defaults:
  - pipeline: document_search_optimization
  - data: qa
  - _self_

task:
  name: default
  type: document-search

metrics:
  - type: ragbits.evaluate.metrics.document_search:DocumentSearchPrecisionRecallF1
    matching_strategy: RougeChunkMatch
    options:
      threshold: 0.5
  - type: ragbits.evaluate.metrics.document_search:DocumentSearchRankedRetrievalMetrics
    weight: -1.0
    matching_strategy: RougeChunkMatch
    options:
      threshold: 0.5


callbacks:
  - type: ragbits.evaluate.callbacks.neptune:NeptuneCallbackConfigurator
    args:
      callback_type: neptune.integrations.optuna:NeptuneCallback
      project: deepsense-ai/ragbits
