defaults:
  - data: qa
  - pipeline: document_search

task:
  name: default
  type: document-search

metrics:
  - type: ragbits.evaluate.metrics.document_search:DocumentSearchPrecisionRecallF1
    matching_strategy: RougeChunkMatch
    options:
      threshold: 0.5
  - type: ragbits.evaluate.metrics.document_search:DocumentSearchRankedRetrievalMetrics
    matching_strategy: RougeChunkMatch
    options:
      threshold: 0.5

neptune:
  project: ragbits
  run: False
