precision_recall_f1:
  type: ragbits.evaluate.metrics.document_search:DocumentSearchPrecisionRecallF1
  config:
    matching_strategy:
      type: RougeChunkMatch
      config:
        threshold: 0.5
