name: Continuous Integration

on:
  push:
    branches: [main, master]

jobs:
  shared:
    uses: ./.github/workflows/shared.yml
  backend:
    uses: ./.github/workflows/be.yml
  frontend:
    uses: ./.github/workflows/fe.yml