name: Continuous Integration

on:
  push:
    branches: [main, master]

jobs:
  shared:
    uses: ./.github/workflows/shared.yml
  main:
    uses: ./.github/workflows/main.yml
  packages:
    needs: main
    if: ${{ needs.main.outputs.packages-changed == 'true' }}
    uses: ./.github/workflows/packages.yml
  ui:
    needs: main
    if: ${{ needs.main.outputs.ui-changed == 'true' }}
    uses: ./.github/workflows/ui.yml