name: Continuous Integration

on:
  pull_request:

jobs:
  shared:
    uses: ./.github/workflows/shared.yml
  pull-request:
    uses: ./.github/workflows/pull-request.yml
  backend:
    uses: ./.github/workflows/be.yml
  frontend:
    uses: ./.github/workflows/fe.yml