name: Main Jobs

on:
  workflow_call:
    outputs:
      packages-changed:
        description: "If the packages were changed"
        value: ${{ jobs.check-changes.outputs.packages-changed }}
      ui-changed:
        description: "If the UI was changed"
        value: ${{ jobs.check-changes.outputs.ui-changed }}

jobs:
  check-changes:
    name: Check source changes
    runs-on: ubuntu-latest
    outputs:
      packages-changed: ${{ steps.filter.outputs.packages-changed }}
      ui-changed: ${{ steps.filter.outputs.ui-changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        id: filter
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          if echo "$changed_files" | grep -qv '^ui/'; then
            echo "packages-changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "packages-changed=false" >> "$GITHUB_OUTPUT"
          fi

          if echo "$changed_files" | grep -q '^ui/'; then
            echo "ui-changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "ui-changed=false" >> "$GITHUB_OUTPUT"
          fi