name: Check examples

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # First job: Generate matrix of examples
  generate-matrix:
    name: Generate examples matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
      examples-count: ${{ steps.generate.outputs.count }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate matrix
        id: generate
        run: |
          matrix=$(bash .github/scripts/list_examples.sh)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          count=$(echo "$matrix" | jq '.example | length')
          echo "count=$count" >> $GITHUB_OUTPUT
          echo "Found $count runnable examples"
          echo "$matrix" | jq .

  # Second job: Run examples in parallel
  examples:
    name: Run example
    runs-on: ubuntu-latest
    needs: generate-matrix
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read

    # Use matrix strategy to run examples in parallel
    strategy:
      fail-fast: false  # Don't stop other examples if one fails
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    services:
      postgres:
        image: pgvector/pgvector:${{ vars.PGVECTOR_IMAGE_TAG || '0.8.0-pg17' }}
        env:
          POSTGRES_USER: ragbits_example
          POSTGRES_PASSWORD: ragbits_example
          POSTGRES_DB: ragbits_example
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      weaviate:
        image: cr.weaviate.io/semitechnologies/weaviate:${{ vars.WEAVIATE_IMAGE_TAG || '1.30.6' }}
        env:
          QUERY_DEFAULTS_LIMIT: 25
          AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: true
          PERSISTENCE_DATA_PATH: /var/lib/weaviate
          ENABLE_API_BASED_MODULES: true
          CLUSTER_HOSTNAME: node1
        ports:
          - 8080:8080
          - 50051:50051
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8080/v1/.well-known/ready || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      grafana:
        image: grafana/otel-lgtm
        ports:
          - 3000:3000
          - 4317:4317
          - 4318:4318

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: ${{ vars.UV_VERSION || '0.6.9' }}

      - name: Run example - ${{ matrix.example }}
        env:
          PR_BRANCH: ${{ github.head_ref }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_KEY: ${{ secrets.GCP_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
        run: |
          echo "$GCP_KEY" | base64 --decode > "$GOOGLE_APPLICATION_CREDENTIALS"
          chmod +x .github/scripts/run_single_example.sh
          ./.github/scripts/run_single_example.sh "${{ matrix.example }}"

  # Summary job: Report overall results
  examples-summary:
    name: Examples summary
    runs-on: ubuntu-latest
    needs: [generate-matrix, examples]
    if: always()
    steps:
      - name: Check results
        run: |
          echo "Examples matrix generation: ${{ needs.generate-matrix.result }}"
          echo "Examples execution: ${{ needs.examples.result }}"
          echo "Total examples: ${{ needs.generate-matrix.outputs.examples-count }}"

          if [[ "${{ needs.generate-matrix.result }}" != "success" ]]; then
            echo "❌ Failed to generate examples matrix"
            exit 1
          fi

          if [[ "${{ needs.examples.result }}" != "success" ]]; then
            echo "❌ Some examples failed"
            exit 1
          fi

          echo "✅ All ${{ needs.generate-matrix.outputs.examples-count }} examples completed successfully"
